apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: ltservices/api-quotation:1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
